server:
  port: 9002

spring :
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=userservice
    username: sa
    password: password
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update
